services:
  ms-producto:
    build:
      context: .
    container_name: producto_service
    environment:
      # Configuración de PostgreSQL
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=ecomercedb
      - POSTGRES_PORT=${POSTGRES_PORT}

      # Configuración de Redis
      - REDIS_HOST=${REDIS_HOST}  # Nombre del contenedor Redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}

    env_file:
      - .env

    ports:
      - "5003:5003"

    restart: always

    networks:
      - red1

networks:
  red1:
    external: true  # Usa la red compartida para la base de datos y redis
