services:
  ms-producto:
    build:
      context: .  # Carpeta con el Dockerfile del microservicio
    container_name: producto_service
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=ecomercedb
      - POSTGRES_PORT=${POSTGRES_PORT}
      - DEV_DATABASE_URI=${DEV_DATABASE_URI}  
    env_file:
      - .env
    ports:
      - "5003:5003"
    restart: always
    networks:
      - red1

networks:
  red1:
    external: true  
